version: '3'

services:
  backend:
    build: ./Backend
    container_name: backend
    command: gunicorn --workers 3 --bind :8000 myproject.wsgi:application
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./myapp
    container_name: frontend
    stdin_open: true
    tty: true
    volumes:
      - ./myapp:/app
    ports:
      - "3000:3000"
